# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_service_pb2 as model__service__pb2


class ModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGrades = channel.unary_unary(
                '/Model/GetGrades',
                request_serializer=model__service__pb2.GradesRequest.SerializeToString,
                response_deserializer=model__service__pb2.Grades.FromString,
                )


class ModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGrades,
                    request_deserializer=model__service__pb2.GradesRequest.FromString,
                    response_serializer=model__service__pb2.Grades.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Model', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Model(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model/GetGrades',
            model__service__pb2.GradesRequest.SerializeToString,
            model__service__pb2.Grades.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
